# Generated by Django 4.2.14 on 2024-08-02 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('correspondant', '0002_alter_correspondant_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondant',
            name='created_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correspondant_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Crée par'),
        ),
    ]
