version: "3.9"

# Définition des services pour l'API
services:
  app_edcp:
    # Configuration de la construction de l'image
    build:
      context: .  # Chemin du contexte de construction (répertoire courant)
      args:     # creation d'un argument appeler dev avec pour valeur true
        - DEV=true

    # Configuration des ports
    ports:
      - "8088:8088"  # Mapping du port du conteneur sur le port de l'hôte

    # Configuration des volumes
    volumes:
      - ./app_edcp:/app_edcp  # Montage du dossier local './app_edcp' dans le dossier '/app_edcp' du conteneur

    # Commande à exécuter lors du démarrage du conteneur
    # Correction de la commande avec le nom correct 'manage.py'
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8088"

    # definition des variables d'environnement des acces de la bd
    environment:
      - DB_HOST=db
      - DB_NAME=edcp_db
      - DB_USER=Uroot_edcp
      - DB_PASS=e_dcp@2023#

    # demarrer premierement la bd
    # depends_on:
    #  - db

  # creation du service de base de donnee
  db:
    image: postgres:13-alpine
    # Configuration des ports
    ports:
      - "5436:5432"  # Mapping du port du conteneur sur le port de l'hôte

    volumes:
      - devedcp-db-data:/var/lib/postgresql/data

    networks:
      - default
    environment:
      - POSTGRES_DB=edcp_db # nom de la bd 7B5e.kZc4d6!Dq
      - POSTGRES_USER=Uroot_edcp # name user of database
      - POSTGRES_PASSWORD=e_dcp@2023#  # password for user of database
      - EMAIL_HOST = 'smtp.office365.com'
      - EMAIL_PORT = 587
      - EMAIL_USE_TLS = True
      - EMAIL_HOST_USER = 'edcp@artci.ci'
      - EMAIL_HOST_PASSWORD = 'ZM7rfPxdS87&bWq$'

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8880:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin_projet_edcp@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin_edcp@1234#.
    depends_on:
      - db


volumes:
  devedcp-db-data:

networks:
  default: