version: "3.9"

services:
  app_edcp:
    build:
      context: .
      args:
        - DEV=true

    ports:
      - "8088:8088"

    volumes:
      - ./app_edcp:/app_edcp

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8088"

    environment:
      - DB_HOST=db
      - DB_NAME=edcp_db
      - DB_USER=Uroot_edcp
      - DB_PASS=e_dcp@2023#

    depends_on:
      - db

  db:
    image: postgres:13-alpine
    ports:
      - "5436:5432"

    volumes:
      - devedcp-db-data:/var/lib/postgresql/data:rw

    networks:
      - default

    environment:
      - POSTGRES_DB=edcp_db
      - POSTGRES_USER=Uroot_edcp
      - POSTGRES_PASSWORD=e_dcp@2023#
      - EMAIL_HOST=smtp.office365.com
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=True
      - EMAIL_HOST_USER=edcp@artci.ci
      - EMAIL_HOST_PASSWORD=ZM7rfPxdS87&bWq$$

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8880:80"

    environment:
      - PGADMIN_DEFAULT_EMAIL=admin_projet_edcp@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin_edcp@1234#.

    depends_on:
      - db

volumes:
  devedcp-db-data:

networks:
  default: