# Generated by Django 4.2.14 on 2024-09-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Codification du champ, à écrire sous forme de slug', max_length=100, unique=True, verbose_name='Label')),
                ('is_sensible', models.BooleanField(default=False, verbose_name='Sensible ?')),
                ('description', models.CharField(blank=True, help_text='Description du champ, affichée sur les formulaire', max_length=255, null=True, verbose_name='Description du champ')),
                ('resume', models.TextField(blank=True, help_text='Paragraphe plus long que la description fournissant des détails sur le champ', max_length=500, null=True, verbose_name='Résumé du champ (texte explicatif)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': "Nom de groupe d'utilisateurs",
                'verbose_name_plural': "Noms de groupes d'utilisateurs",
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Nom du Pays')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name="Secteur d'Activité")),
                ('sensible', models.BooleanField(verbose_name='Est Sensible')),
                ('ordre', models.IntegerField(verbose_name="Ordre d'Affichage")),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Codification du champ, à écrire sous forme de slug', max_length=100, unique=True, verbose_name='Label')),
                ('is_sensible', models.BooleanField(default=False, verbose_name='Sensible ?')),
                ('description', models.CharField(blank=True, help_text='Description du champ, affichée sur les formulaire', max_length=255, null=True, verbose_name='Description du champ')),
                ('resume', models.TextField(blank=True, help_text='Paragraphe plus long que la description fournissant des détails sur le champ', max_length=500, null=True, verbose_name='Résumé du champ (texte explicatif)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': "Statut de demande ou d'analyse",
                'verbose_name_plural': "Statuts de demandes ou d'analyses",
            },
        ),
        migrations.CreateModel(
            name='TypeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Type de Client')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description du Type de Client')),
                ('sensible', models.BooleanField(default=False, null=True, verbose_name='Est Sensible')),
                ('ordre', models.IntegerField(default=0, null=True, verbose_name="Ordre d'Affichage")),
            ],
            options={
                'verbose_name': 'Type Client',
                'verbose_name_plural': 'Types Clients',
            },
        ),
        migrations.CreateModel(
            name='TypePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name="Type de pièce d'identité")),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description du Type de pièce')),
                ('sensible', models.BooleanField(default=False, null=True, verbose_name='Est Sensible')),
                ('ordre', models.IntegerField(default=0, null=True, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Type de pièce',
                'verbose_name_plural': 'Types de pièces',
            },
        ),
    ]
