# Generated by Django 4.2.14 on 2024-09-13 11:27

import base_edcp.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
        ('demande_auto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Codification du champ, à écrire sous forme de slug', max_length=100, unique=True, verbose_name='Label')),
                ('is_sensible', models.BooleanField(default=False, verbose_name='Sensible ?')),
                ('description', models.CharField(blank=True, help_text='Description du champ, affichée sur les formulaire', max_length=255, null=True, verbose_name='Description du champ')),
                ('resume', models.TextField(blank=True, help_text='Paragraphe plus long que la description fournissant des détails sur le champ', max_length=500, null=True, verbose_name='Résumé du champ (texte explicatif)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Categorie de données',
                'verbose_name_plural': 'Categories de données',
            },
        ),
        migrations.CreateModel(
            name='FondementJuridique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Codification du champ, à écrire sous forme de slug', max_length=100, unique=True, verbose_name='Label')),
                ('is_sensible', models.BooleanField(default=False, verbose_name='Sensible ?')),
                ('description', models.CharField(blank=True, help_text='Description du champ, affichée sur les formulaire', max_length=255, null=True, verbose_name='Description du champ')),
                ('resume', models.TextField(blank=True, help_text='Paragraphe plus long que la description fournissant des détails sur le champ', max_length=500, null=True, verbose_name='Résumé du champ (texte explicatif)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Fondement juridique',
                'verbose_name_plural': 'Fondements juridiques',
            },
        ),
        migrations.CreateModel(
            name='ModeInterconnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Codification du champ, à écrire sous forme de slug', max_length=100, unique=True, verbose_name='Label')),
                ('is_sensible', models.BooleanField(default=False, verbose_name='Sensible ?')),
                ('description', models.CharField(blank=True, help_text='Description du champ, affichée sur les formulaire', max_length=255, null=True, verbose_name='Description du champ')),
                ('resume', models.TextField(blank=True, help_text='Paragraphe plus long que la description fournissant des détails sur le champ', max_length=500, null=True, verbose_name='Résumé du champ (texte explicatif)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': "Mode d'interconnexion",
                'verbose_name_plural': "Modes d'interconnexion",
            },
        ),
        migrations.CreateModel(
            name='ModeRecueilConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Codification du champ, à écrire sous forme de slug', max_length=100, unique=True, verbose_name='Label')),
                ('is_sensible', models.BooleanField(default=False, verbose_name='Sensible ?')),
                ('description', models.CharField(blank=True, help_text='Description du champ, affichée sur les formulaire', max_length=255, null=True, verbose_name='Description du champ')),
                ('resume', models.TextField(blank=True, help_text='Paragraphe plus long que la description fournissant des détails sur le champ', max_length=500, null=True, verbose_name='Résumé du champ (texte explicatif)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Mode de recueil de consentement',
                'verbose_name_plural': 'Modes de recueil de consentement',
            },
        ),
        migrations.CreateModel(
            name='ModeTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Codification du champ, à écrire sous forme de slug', max_length=100, unique=True, verbose_name='Label')),
                ('is_sensible', models.BooleanField(default=False, verbose_name='Sensible ?')),
                ('description', models.CharField(blank=True, help_text='Description du champ, affichée sur les formulaire', max_length=255, null=True, verbose_name='Description du champ')),
                ('resume', models.TextField(blank=True, help_text='Paragraphe plus long que la description fournissant des détails sur le champ', max_length=500, null=True, verbose_name='Résumé du champ (texte explicatif)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Mode de transfert des données',
                'verbose_name_plural': 'Modes de transfert des données',
            },
        ),
        migrations.CreateModel(
            name='TypeDestinataireTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Codification du champ, à écrire sous forme de slug', max_length=100, unique=True, verbose_name='Label')),
                ('is_sensible', models.BooleanField(default=False, verbose_name='Sensible ?')),
                ('description', models.CharField(blank=True, help_text='Description du champ, affichée sur les formulaire', max_length=255, null=True, verbose_name='Description du champ')),
                ('resume', models.TextField(blank=True, help_text='Paragraphe plus long que la description fournissant des détails sur le champ', max_length=500, null=True, verbose_name='Résumé du champ (texte explicatif)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Type de destinataire des données',
                'verbose_name_plural': 'Types de destinataire des données',
            },
        ),
        migrations.AddField(
            model_name='demandeauto',
            name='description_traitement',
            field=models.TextField(blank=True, null=True, verbose_name='Description du traitement'),
        ),
        migrations.AddField(
            model_name='demandeautotraitement',
            name='autre_donnees_traitees',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Autre données traitées'),
        ),
        migrations.AddField(
            model_name='demandeautotraitement',
            name='autre_mode_consentement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Autre mode de recueil du consentement'),
        ),
        migrations.AddField(
            model_name='demandeautotraitement',
            name='autre_sous_finalites',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Autre sous-finalité'),
        ),
        migrations.AddField(
            model_name='demandeautotraitement',
            name='description_fondement',
            field=models.TextField(blank=True, null=True, verbose_name='Description du fondement juridique'),
        ),
        migrations.AddField(
            model_name='demandeautotraitement',
            name='file_cgu',
            field=models.FileField(blank=True, help_text='Formats acceptés images et documents PDF : jpg, jpeg, png, pdf. Taille limite: 8 Mb.', null=True, upload_to='docs/demande_auto', validators=[base_edcp.validators.validate_files, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name="Conditions Générales d'Utilisation"),
        ),
        migrations.AddField(
            model_name='demandeautotraitement',
            name='file_consentement',
            field=models.FileField(blank=True, help_text='Formats acceptés images et documents PDF : jpg, jpeg, png, pdf. Taille limite: 8 Mb.', null=True, upload_to='docs/demande_auto', validators=[base_edcp.validators.validate_files, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Preuve du recueil du consentement'),
        ),
        migrations.AlterField(
            model_name='demandeautotraitement',
            name='procedures',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Procédures de gestion des droits des personnes'),
        ),
        migrations.CreateModel(
            name='TypeDonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Codification du champ, à écrire sous forme de slug', max_length=100, unique=True, verbose_name='Label')),
                ('is_sensible', models.BooleanField(default=False, verbose_name='Sensible ?')),
                ('description', models.CharField(blank=True, help_text='Description du champ, affichée sur les formulaire', max_length=255, null=True, verbose_name='Description du champ')),
                ('resume', models.TextField(blank=True, help_text='Paragraphe plus long que la description fournissant des détails sur le champ', max_length=500, null=True, verbose_name='Résumé du champ (texte explicatif)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('categorie_donnees', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demande_auto.categoriedonnees', verbose_name='Categorie de données')),
            ],
            options={
                'verbose_name': 'Type de données personnelles',
                'verbose_name_plural': 'Types de données personnelles',
            },
        ),
        migrations.CreateModel(
            name='TransfertDonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('destinataire_transfert', models.CharField(blank=True, max_length=255, null=True, verbose_name='Destinataire données')),
                ('mode_transfert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demande_auto.modetransfert', verbose_name='Mode de transfert des données')),
                ('pays', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='options.pays', verbose_name='Pays de destination')),
                ('type_destinataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demande_auto.typedestinatairetransfert', verbose_name='Type de Destinataire')),
            ],
            options={
                'verbose_name': 'Transfert de données',
                'verbose_name_plural': 'Transferts de données',
            },
        ),
        migrations.CreateModel(
            name='InterConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('destinataire_interco', models.CharField(max_length=100, null=True, verbose_name='Destinataire des données')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name="Description de l'interconnexion")),
                ('mode_interconnexion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demande_auto.modeinterconnexion', verbose_name="Mode d'interconnexion")),
            ],
            options={
                'verbose_name': 'Interconnexion',
                'verbose_name_plural': 'Interconnexions',
            },
        ),
        migrations.AddField(
            model_name='demandeautotraitement',
            name='donnees_traitees',
            field=models.ManyToManyField(to='demande_auto.typedonnees', verbose_name='Données traitees'),
        ),
        migrations.AddField(
            model_name='demandeautotraitement',
            name='interconnexions',
            field=models.ManyToManyField(blank=True, to='demande_auto.interconnexion', verbose_name='Interconnexions de données'),
        ),
        migrations.AddField(
            model_name='demandeautotraitement',
            name='mode_consentement',
            field=models.ManyToManyField(to='demande_auto.moderecueilconsent', verbose_name='Modes de recueil du consentement'),
        ),
        migrations.AddField(
            model_name='demandeautotraitement',
            name='transferts',
            field=models.ManyToManyField(blank=True, to='demande_auto.transfertdonnees', verbose_name='Transferts de données'),
        ),
        migrations.AlterField(
            model_name='demandeautotraitement',
            name='fondement_juridique',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demande_auto.fondementjuridique', verbose_name='Fondement Juridique'),
        ),
    ]
