# Generated by Django 4.2.14 on 2024-08-22 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demande', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAuto',
            fields=[
                ('demande_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demande.demande')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Description du traitement')),
                ('consent_docs', models.BooleanField(default=False, verbose_name='Consentement Documents')),
            ],
            options={
                'verbose_name': "Demande d'autorisation",
                'verbose_name_plural': "Demandes d'autorisation",
            },
            bases=('demande.demande',),
        ),
        migrations.CreateModel(
            name='EchelleNotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Codification du champ, à écrire sous forme de slug', max_length=100, unique=True, verbose_name='Label')),
                ('is_sensible', models.BooleanField(default=False, verbose_name='Sensible ?')),
                ('description', models.CharField(blank=True, help_text='Description du champ, affichée sur les formulaire', max_length=255, null=True, verbose_name='Description du champ')),
                ('resume', models.TextField(blank=True, help_text='Paragraphe plus long que la description fournissant des détails sur le champ', max_length=500, null=True, verbose_name='Résumé du champ (texte explicatif)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('valeur', models.IntegerField(default=0, verbose_name='Valeur')),
            ],
            options={
                'verbose_name': 'Echelle de notation',
                'verbose_name_plural': 'Echelles de notation',
            },
        ),
        migrations.CreateModel(
            name='Finalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Codification du champ, à écrire sous forme de slug', max_length=100, unique=True, verbose_name='Label')),
                ('is_sensible', models.BooleanField(default=False, verbose_name='Sensible ?')),
                ('description', models.CharField(blank=True, help_text='Description du champ, affichée sur les formulaire', max_length=255, null=True, verbose_name='Description du champ')),
                ('resume', models.TextField(blank=True, help_text='Paragraphe plus long que la description fournissant des détails sur le champ', max_length=500, null=True, verbose_name='Résumé du champ (texte explicatif)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersConcernee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Codification du champ, à écrire sous forme de slug', max_length=100, unique=True, verbose_name='Label')),
                ('is_sensible', models.BooleanField(default=False, verbose_name='Sensible ?')),
                ('description', models.CharField(blank=True, help_text='Description du champ, affichée sur les formulaire', max_length=255, null=True, verbose_name='Description du champ')),
                ('resume', models.TextField(blank=True, help_text='Paragraphe plus long que la description fournissant des détails sur le champ', max_length=500, null=True, verbose_name='Résumé du champ (texte explicatif)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie de personnes concernées',
                'verbose_name_plural': 'Catégories de personnes concernées',
            },
        ),
        migrations.CreateModel(
            name='DemandeAutoBiometrie',
            fields=[
                ('demandeauto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demande_auto.demandeauto')),
                ('types_dispositifs', models.CharField(blank=True, max_length=255, null=True, verbose_name='Types de dispositifs')),
                ('nb_dispositifs', models.IntegerField(blank=True, null=True, verbose_name='Nombre de dispositifs')),
                ('mesures_securite', models.TextField(blank=True, max_length=500, null=True, verbose_name='Mesures de Securité')),
            ],
            bases=('demande_auto.demandeauto',),
        ),
        migrations.CreateModel(
            name='DemandeAutoTraitement',
            fields=[
                ('demandeauto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demande_auto.demandeauto')),
                ('fondement_juridique', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fondement Juridique')),
                ('procedures', models.TextField(blank=True, max_length=500, null=True, verbose_name='Procédures')),
                ('mesures_securite', models.TextField(blank=True, max_length=500, null=True, verbose_name='Mesures de Securité')),
            ],
            bases=('demande_auto.demandeauto',),
        ),
        migrations.CreateModel(
            name='DemandeAutoTransfert',
            fields=[
                ('demandeauto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demande_auto.demandeauto')),
                ('destination', models.CharField(blank=True, max_length=255, null=True, verbose_name='Destination du transfert')),
                ('motif_transfert', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motif du Transfert')),
                ('mesures_securite', models.TextField(blank=True, max_length=500, null=True, verbose_name='Mesures de Securité')),
            ],
            bases=('demande_auto.demandeauto',),
        ),
        migrations.CreateModel(
            name='DemandeAutoVideo',
            fields=[
                ('demandeauto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demande_auto.demandeauto')),
                ('types_cameras', models.CharField(blank=True, max_length=255, null=True, verbose_name='Types de cameras')),
                ('nb_cameras', models.IntegerField(blank=True, null=True, verbose_name='Nombre de cameras')),
                ('mesures_securite', models.TextField(blank=True, max_length=500, null=True, verbose_name='Mesures de Securité')),
            ],
            bases=('demande_auto.demandeauto',),
        ),
        migrations.CreateModel(
            name='TypeDemandeAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Codification du champ, à écrire sous forme de slug', max_length=100, unique=True, verbose_name='Label')),
                ('is_sensible', models.BooleanField(default=False, verbose_name='Sensible ?')),
                ('description', models.CharField(blank=True, help_text='Description du champ, affichée sur les formulaire', max_length=255, null=True, verbose_name='Description du champ')),
                ('resume', models.TextField(blank=True, help_text='Paragraphe plus long que la description fournissant des détails sur le champ', max_length=500, null=True, verbose_name='Résumé du champ (texte explicatif)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('finalites', models.ManyToManyField(related_name='types_demande', to='demande_auto.finalite', verbose_name='Finalités liées à ce type de demande')),
            ],
            options={
                'verbose_name': 'Type de demande',
                'verbose_name_plural': 'Types de demande',
            },
        ),
        migrations.CreateModel(
            name='SousFinalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Codification du champ, à écrire sous forme de slug', max_length=100, unique=True, verbose_name='Label')),
                ('is_sensible', models.BooleanField(default=False, verbose_name='Sensible ?')),
                ('description', models.CharField(blank=True, help_text='Description du champ, affichée sur les formulaire', max_length=255, null=True, verbose_name='Description du champ')),
                ('resume', models.TextField(blank=True, help_text='Paragraphe plus long que la description fournissant des détails sur le champ', max_length=500, null=True, verbose_name='Résumé du champ (texte explicatif)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('finalite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demande_auto.finalite', verbose_name='Finalité')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='demandeauto',
            name='finalite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demande_auto.finalite', verbose_name='Finalité'),
        ),
        migrations.AddField(
            model_name='demandeauto',
            name='personnes_concernees',
            field=models.ManyToManyField(blank=True, to='demande_auto.persconcernee', verbose_name='Personnes Concernées'),
        ),
        migrations.AddField(
            model_name='demandeauto',
            name='sous_finalites',
            field=models.ManyToManyField(blank=True, to='demande_auto.sousfinalite', verbose_name='Sous-finalités'),
        ),
        migrations.AddField(
            model_name='demandeauto',
            name='type_demande',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='demande_auto.typedemandeauto', verbose_name="Type de Demande d'Autorisation"),
        ),
    ]
