# Generated by Django 4.2.14 on 2024-08-22 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demande_auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeauto',
            name='type_demande',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='demande_auto.typedemandeauto', verbose_name="Type de Demande d'Autorisation"),
        ),
    ]
