# Generated by Django 4.2.14 on 2024-08-22 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correspondant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondant',
            name='type_dpo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='correspondant.typedpo', verbose_name='Type de Correspondant'),
        ),
    ]
