# Generated by Django 4.2.14 on 2024-07-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondant', '0002_alter_correspondant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='correspondant',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approuvé'),
        ),
    ]
