# Generated by Django 4.2.14 on 2024-08-03 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('correspondant', '0003_alter_correspondant_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_created', to=settings.AUTH_USER_MODEL, verbose_name='Crée par'),
        ),
        migrations.AlterField(
            model_name='correspondant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondant_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur'),
        ),
    ]
