# Generated by Django 4.2.14 on 2024-07-26 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correspondant', '0003_correspondant_is_active_correspondant_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondant',
            name='type_dpo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='correspondant.typedpo', verbose_name='Type de Correspondant'),
        ),
    ]
