# Generated by Django 4.2.14 on 2024-08-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondant', '0004_alter_correspondant_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondant',
            name='file_attestation_travail',
            field=models.FileField(blank=True, null=True, upload_to='correspondant/docs', verbose_name='Attestation de travail'),
        ),
        migrations.AddField(
            model_name='correspondant',
            name='file_casier_judiciaire',
            field=models.FileField(blank=True, help_text='datant de moins de 3 mois', null=True, upload_to='correspondant/docs', verbose_name='Casier judiciaire'),
        ),
        migrations.AddField(
            model_name='correspondant',
            name='file_certificat_nationalite',
            field=models.FileField(blank=True, null=True, upload_to='correspondant/docs', verbose_name='Certificat de nationalité'),
        ),
        migrations.AddField(
            model_name='correspondant',
            name='file_cv',
            field=models.FileField(blank=True, null=True, upload_to='correspondant/docs', verbose_name='CV'),
        ),
        migrations.AddField(
            model_name='correspondant',
            name='file_lettre_acceptation',
            field=models.FileField(blank=True, null=True, upload_to='correspondant/docs', verbose_name='Lettre d\x07cceptation'),
        ),
        migrations.AddField(
            model_name='correspondant',
            name='file_lettre_designation',
            field=models.FileField(blank=True, null=True, upload_to='correspondant/docs', verbose_name='Lettre de désignation'),
        ),
    ]
