# Generated by Django 4.2.14 on 2024-08-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondant', '0005_correspondant_file_attestation_travail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondant',
            name='file_attestation_travail',
            field=models.FileField(blank=True, null=True, upload_to='docs/correspondant', verbose_name='Attestation de travail'),
        ),
        migrations.AlterField(
            model_name='correspondant',
            name='file_casier_judiciaire',
            field=models.FileField(blank=True, help_text='datant de moins de 3 mois', null=True, upload_to='docs/correspondant', verbose_name='Casier judiciaire'),
        ),
        migrations.AlterField(
            model_name='correspondant',
            name='file_certificat_nationalite',
            field=models.FileField(blank=True, null=True, upload_to='docs/correspondant', verbose_name='Certificat de nationalité'),
        ),
        migrations.AlterField(
            model_name='correspondant',
            name='file_cv',
            field=models.FileField(blank=True, null=True, upload_to='docs/correspondant', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='correspondant',
            name='file_lettre_acceptation',
            field=models.FileField(blank=True, null=True, upload_to='docs/correspondant', verbose_name="Lettre d'acceptation"),
        ),
        migrations.AlterField(
            model_name='correspondant',
            name='file_lettre_designation',
            field=models.FileField(blank=True, null=True, upload_to='docs/correspondant', verbose_name='Lettre de désignation'),
        ),
    ]
