# Generated by Django 4.2.14 on 2024-08-05 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0010_alter_user_avatar_alter_user_consentement'),
        ('correspondant', '0006_alter_correspondant_file_attestation_travail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondant',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondants', to='base_edcp.enregistrement', verbose_name='Organisation'),
        ),
    ]
