# Generated by Django 4.2.14 on 2024-08-05 17:46

import base_edcp.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondant', '0007_alter_correspondant_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondant',
            name='profile_completed',
            field=models.BooleanField(default=False, verbose_name='Profil complet'),
        ),
        migrations.AlterField(
            model_name='correspondant',
            name='file_attestation_travail',
            field=models.FileField(blank=True, help_text='Formats acceptés images et documents PDF : jpg, jpeg, png, pdf. Taille limite: 8 Mb.', null=True, upload_to='docs/correspondant', validators=[base_edcp.validators.validate_files, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Attestation de travail'),
        ),
        migrations.AlterField(
            model_name='correspondant',
            name='file_casier_judiciaire',
            field=models.FileField(blank=True, help_text='Formats acceptés images et documents PDF : jpg, jpeg, png, pdf. Taille limite: 8 Mb.', null=True, upload_to='docs/correspondant', validators=[base_edcp.validators.validate_files, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Casier judiciaire'),
        ),
        migrations.AlterField(
            model_name='correspondant',
            name='file_certificat_nationalite',
            field=models.FileField(blank=True, help_text='Formats acceptés images et documents PDF : jpg, jpeg, png, pdf. Taille limite: 8 Mb.', null=True, upload_to='docs/correspondant', validators=[base_edcp.validators.validate_files, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Certificat de nationalité'),
        ),
        migrations.AlterField(
            model_name='correspondant',
            name='file_cv',
            field=models.FileField(blank=True, help_text='Formats acceptés images et documents PDF : jpg, jpeg, png, pdf. Taille limite: 8 Mb.', null=True, upload_to='docs/correspondant', validators=[base_edcp.validators.validate_files, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='correspondant',
            name='file_lettre_acceptation',
            field=models.FileField(blank=True, help_text='Formats acceptés images et documents PDF : jpg, jpeg, png, pdf. Taille limite: 8 Mb.', null=True, upload_to='docs/correspondant', validators=[base_edcp.validators.validate_files, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name="Lettre d'acceptation"),
        ),
        migrations.AlterField(
            model_name='correspondant',
            name='file_lettre_designation',
            field=models.FileField(blank=True, help_text='Formats acceptés images et documents PDF : jpg, jpeg, png, pdf. Taille limite: 8 Mb.', null=True, upload_to='docs/correspondant', validators=[base_edcp.validators.validate_files, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Lettre de désignation'),
        ),
    ]
