# Generated by Django 4.2.14 on 2024-08-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondant', '0008_correspondant_profile_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondant',
            name='is_rejected',
            field=models.BooleanField(default=False, verbose_name='Refusé'),
        ),
    ]
