# Generated by Django 4.2.14 on 2024-07-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enregistrement',
            name='has_dpo',
            field=models.BooleanField(default=False, verbose_name='A désigné un Correspondant'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_dpo',
            field=models.BooleanField(default=False),
        ),
    ]
