# Generated by Django 3.2.25 on 2024-07-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name="Secteur d'Activité")),
                ('sensible', models.BooleanField(verbose_name='Est Sensible')),
                ('ordre', models.IntegerField(verbose_name="Ordre d'Affichage")),
            ],
            options={
                'verbose_name': 'Secteur',
                'verbose_name_plural': 'Secteurs',
            },
        ),
        migrations.CreateModel(
            name='TypeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Type de Client')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='Description du Type de Client')),
                ('sensible', models.BooleanField(null=True, verbose_name='Est Sensible')),
                ('ordre', models.IntegerField(null=True, verbose_name="Ordre d'Affichage")),
            ],
            options={
                'verbose_name': 'Type Client',
                'verbose_name_plural': 'Type Clients',
            },
        ),
    ]
