# Generated by Django 4.2.14 on 2024-07-29 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Donnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('sensible', models.BooleanField(default=False, verbose_name='Sensible')),
                ('duree_conservation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Durée de Conservation')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Hebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Interco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.CharField(max_length=255, verbose_name='Destinataire')),
                ('mode', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mode')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Legitimite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='ModeRecueilConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='SecuritePhysique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='SupportCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=255, verbose_name='Pays')),
                ('destinataire', models.CharField(max_length=255, verbose_name='Destinataire')),
                ('mode', models.CharField(max_length=255, verbose_name='Mode')),
                ('type_destinataire', models.CharField(max_length=255, verbose_name='Type de Destinataire')),
            ],
        ),
        migrations.CreateModel(
            name='TypeDemandeAutorisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('autorisation_prealable', 'Autorisation Préalable'), ('biometrie', 'Biométrie'), ('videosurveillance', 'Vidéosurveillance'), ('transfert_donnees_hors_espace_cdeao', 'Transfert de Données Hors Espace CEDEAO'), ('notification_violation_donnees_personnelles', 'Notification de Violation des Données Personnelles'), ('violation_conformite', 'Violation de la Conformité'), ('analyse_impact_protection_donnees_personnelles', 'Analyse d’Impact sur la Protection des Données Personnelles'), ('mise_en_conformite', 'Mise en Conformité'), ('declaration_normale', 'Déclaration Normale'), ('agreement', 'Agrément'), ('attestation_conformite', 'Attestation Conformité'), ('geolocalisation', 'Géolocalisation')], max_length=255, unique=True, verbose_name="Type de Demande d'Autorisation")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='finalite',
            name='ordre',
        ),
        migrations.RemoveField(
            model_name='finalite',
            name='sensible',
        ),
        migrations.AddField(
            model_name='finalite',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='persconcernee',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='sousfinalite',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='finalite',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='fonction',
            name='fonction',
            field=models.CharField(max_length=100, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='fondjuridique',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='habilitation',
            name='created',
            field=models.DateField(verbose_name='Date de Création'),
        ),
        migrations.AlterField(
            model_name='persconcernee',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='persconcernee',
            name='ordre',
            field=models.IntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='persconcernee',
            name='sensible',
            field=models.BooleanField(default=False, verbose_name='Sensible'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(max_length=100, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='sousfinalite',
            name='finalite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_finalites', to='base_edcp.finalite', verbose_name='Finalité'),
        ),
        migrations.AlterField(
            model_name='sousfinalite',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='sousfinalite',
            name='ordre',
            field=models.IntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='sousfinalite',
            name='sensible',
            field=models.BooleanField(default=False, verbose_name='Sensible'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email Vérifié'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_dpo',
            field=models.BooleanField(default=False, verbose_name='Est un Correspondant'),
        ),
        migrations.CreateModel(
            name='Securite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authentications', models.ManyToManyField(related_name='securite_auth', to='base_edcp.authentication', verbose_name='Authentification')),
                ('backups', models.ManyToManyField(related_name='securite_backup', to='base_edcp.backup', verbose_name='Backup')),
                ('hebergement', models.ManyToManyField(related_name='securite_hebergement', to='base_edcp.hebergement', verbose_name='Hébergement')),
                ('protect_physique', models.ManyToManyField(related_name='securite_protect', to='base_edcp.securitephysique', verbose_name='Protection Physique')),
                ('supports_collecte', models.ManyToManyField(related_name='securite_supports', to='base_edcp.supportcollecte', verbose_name='Supports de Collecte')),
            ],
        ),
        migrations.CreateModel(
            name='DonneeTraitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('sensible', models.BooleanField(default=False, verbose_name='Sensible')),
                ('duree_conservation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Durée de Conservation')),
                ('id_categorie', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Catégorie')),
                ('donnees', models.ManyToManyField(related_name='donnees_traitees', to='base_edcp.donnee', verbose_name='Données')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('organisation_id', models.CharField(max_length=255, verbose_name="ID de l'Organisation")),
                ('organisation_name', models.CharField(max_length=255, verbose_name="Nom de l'Organisation")),
                ('organisation_phone', models.CharField(max_length=255, verbose_name="Téléphone de l'Organisation")),
                ('consent_dcp', models.BooleanField(default=False, verbose_name='Consentement DCP')),
                ('consent_docs', models.BooleanField(default=False, verbose_name='Consentement Documents')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Résumé')),
                ('traitement_sensible', models.BooleanField(default=False, verbose_name='Traitement Sensible')),
                ('procedure_droit_persones', models.TextField(blank=True, null=True, verbose_name='Procédure Droit des Personnes')),
                ('donnees_traitees', models.ManyToManyField(to='base_edcp.donneetraitee', verbose_name='Données Traitées')),
                ('finalite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_edcp.finalite', verbose_name='Finalité')),
                ('interco', models.ManyToManyField(to='base_edcp.interco', verbose_name='Interconnexions')),
                ('legitimite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_edcp.legitimite', verbose_name='Légitimité')),
                ('modes_recueil_consent', models.ManyToManyField(to='base_edcp.moderecueilconsent', verbose_name='Modes de Recueil de Consentement')),
                ('personnes_concernees', models.ManyToManyField(to='base_edcp.persconcernee', verbose_name='Personnes Concernées')),
                ('securite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_edcp.securite', verbose_name='Sécurité')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_edcp.status', verbose_name='Statut')),
                ('transferts', models.ManyToManyField(to='base_edcp.transfert', verbose_name='Transferts')),
                ('type_demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_edcp.typedemandeautorisation', verbose_name="Type de Demande d'Autorisation")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Exemple de Modèle',
                'verbose_name_plural': 'Exemples de Modèles',
            },
        ),
    ]
