# Generated by Django 4.2.14 on 2024-09-10 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
