# Generated by Django 3.2.25 on 2024-07-17 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0002_casexemption_categoriedcp_categorietrait_pays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('sensible', models.CharField(max_length=100)),
                ('ordre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FondJuridique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PersConcernee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, null=True)),
                ('sensible', models.BooleanField()),
                ('ordre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True, verbose_name="Nom d'Utilisateur")),
                ('avatar', models.FileField(blank=True, max_length=255, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('nom', models.CharField(max_length=225, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=255, verbose_name='Prénoms')),
                ('organisation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Organisation')),
                ('telephone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Téléphone')),
                ('fonction', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fonction')),
                ('consentement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Consentement')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Est Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Est Membre du Personnel')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='SousFinalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('sensible', models.BooleanField()),
                ('ordre', models.IntegerField()),
                ('finalite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_edcp.finalite')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de création')),
                ('is_read', models.BooleanField(default=False, verbose_name='Est lu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='base_edcp.user', verbose_name='Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Enregistrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('raisonsociale', models.CharField(max_length=100, verbose_name='Raison Sociale')),
                ('representant', models.CharField(max_length=100, verbose_name='Représentant')),
                ('rccm', models.CharField(max_length=100, null=True, verbose_name='RCCM')),
                ('secteur_description', models.CharField(max_length=100, null=True, verbose_name='Description du Secteur')),
                ('presentation', models.CharField(max_length=255, null=True, verbose_name='Présentation')),
                ('telephone', models.CharField(max_length=20, null=True, verbose_name='Téléphone')),
                ('email_contact', models.CharField(max_length=100, null=True, verbose_name='Email de Contact')),
                ('site_web', models.CharField(max_length=100, null=True, verbose_name='Site Web')),
                ('ville', models.CharField(max_length=100, null=True, verbose_name='Ville')),
                ('adresse_geo', models.CharField(max_length=100, null=True, verbose_name='Adresse Géographique')),
                ('adresse_bp', models.CharField(max_length=100, null=True, verbose_name='Boîte Postale')),
                ('gmaps_link', models.CharField(max_length=255, null=True, verbose_name='Lien Google Maps')),
                ('effectif', models.IntegerField(null=True, verbose_name='Effectif')),
                ('pays', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_edcp.pays', verbose_name='Pays')),
                ('secteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_edcp.secteur', verbose_name="Secteur d'Activité")),
                ('typeclient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_edcp.typeclient', verbose_name='Type de Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_edcp.user', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Enregistrement',
                'verbose_name_plural': 'Enregistrements',
            },
        ),
    ]
