# Generated by Django 4.2.14 on 2024-07-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0002_remove_user_login_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrement',
            name='adresse_bp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Boîte Postale'),
        ),
        migrations.AlterField(
            model_name='enregistrement',
            name='adresse_geo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresse Géographique'),
        ),
        migrations.AlterField(
            model_name='enregistrement',
            name='gmaps_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lien Google Maps'),
        ),
        migrations.AlterField(
            model_name='enregistrement',
            name='raisonsociale',
            field=models.CharField(max_length=100, verbose_name='Nom ou raison Sociale'),
        ),
        migrations.AlterField(
            model_name='enregistrement',
            name='rccm',
            field=models.CharField(max_length=100, null=True, verbose_name='Numéro RCCM'),
        ),
        migrations.AlterField(
            model_name='enregistrement',
            name='representant',
            field=models.CharField(max_length=100, verbose_name='Représentant légal'),
        ),
    ]
