# Generated by Django 4.2.14 on 2024-08-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='secteur',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description du Secteur'),
        ),
    ]
