# Generated by Django 3.2.25 on 2024-07-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0002_casexemption_categoriedcp_categorietrait_pays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('sensible', models.CharField(max_length=100)),
                ('ordre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FondJuridique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
