# Generated by Django 4.2.14 on 2024-08-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0003_secteur_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pays',
            name='code',
            field=models.CharField(default='CI', max_length=50, verbose_name='Code du Pays'),
            preserve_default=False,
        ),
    ]
