# Generated by Django 3.2.25 on 2024-07-17 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0003_enregistrement_finalite_fonction_fondjuridique_notification_persconcernee_role_sousfinalite_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_autorisation', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enregistrement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorisations', to='base_edcp.enregistrement')),
            ],
        ),
    ]
