# Generated by Django 4.2.14 on 2024-07-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='enregistrement',
            name='file_piece',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Pièce d\\identité'),
        ),
        migrations.AddField(
            model_name='enregistrement',
            name='file_rccm',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Copie du Registre du Commerce'),
        ),
    ]
