# Generated by Django 3.2.25 on 2024-07-17 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0004_autorisation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secteur',
            options={},
        ),
        migrations.AlterModelOptions(
            name='typeclient',
            options={'verbose_name': 'Type Client', 'verbose_name_plural': 'Types Clients'},
        ),
        migrations.CreateModel(
            name='JournalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('transaction', models.CharField(max_length=100)),
                ('cible', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_edcp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Habilitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_edcp.fonction')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_edcp.role')),
            ],
        ),
    ]
