# Generated by Django 4.2.14 on 2024-08-13 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0004_pays_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrement',
            name='type_piece',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_edcp.typepiece', verbose_name="Type de pièce d'identité"),
        ),
    ]
