# Generated by Django 4.2.14 on 2024-07-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0004_enregistrement_file_piece_enregistrement_file_rccm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrement',
            name='file_piece',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name="Pièce d'identité"),
        ),
    ]
