# Generated by Django 4.2.14 on 2024-07-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0004_typepiece_remove_enregistrement_secteur_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeclient',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description du Type de Client'),
        ),
        migrations.AlterField(
            model_name='typeclient',
            name='ordre',
            field=models.IntegerField(default=0, null=True, verbose_name="Ordre d'Affichage"),
        ),
        migrations.AlterField(
            model_name='typeclient',
            name='sensible',
            field=models.BooleanField(default=False, null=True, verbose_name='Est Sensible'),
        ),
        migrations.AlterField(
            model_name='typepiece',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description du Type de pièce'),
        ),
        migrations.AlterField(
            model_name='typepiece',
            name='ordre',
            field=models.IntegerField(default=0, null=True, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='typepiece',
            name='sensible',
            field=models.BooleanField(default=False, null=True, verbose_name='Est Sensible'),
        ),
    ]
