# Generated by Django 4.2.14 on 2024-07-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0005_alter_enregistrement_file_piece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrement',
            name='presentation',
            field=models.TextField(max_length=255, null=True, verbose_name="Présentation de l'activité"),
        ),
    ]
