# Generated by Django 4.2.14 on 2024-07-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0003_user_email_verified'),
        ('base_edcp', '0005_alter_typeclient_description_alter_typeclient_ordre_and_more'),
    ]

    operations = [
    ]
