# Generated by Django 4.2.14 on 2024-08-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0006_alter_enregistrement_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrement',
            name='file_piece',
            field=models.FileField(blank=True, null=True, upload_to='enregistrement/docs', verbose_name="Pièce d'identité"),
        ),
        migrations.AlterField(
            model_name='enregistrement',
            name='file_rccm',
            field=models.FileField(blank=True, null=True, upload_to='enregistrement/docs', verbose_name='Copie du Registre du Commerce'),
        ),
        migrations.AlterField(
            model_name='enregistrement',
            name='gmaps_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Lien Google Maps'),
        ),
        migrations.AlterField(
            model_name='enregistrement',
            name='site_web',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Site Web'),
        ),
    ]
