# Generated by Django 4.2.14 on 2024-08-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0007_alter_enregistrement_file_piece_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enregistrement',
            name='file_mandat',
            field=models.FileField(blank=True, help_text="Si vous n'êtes pas le représentant légal, Joindre un mandat signé par le représentatnt légal de l'organisation", null=True, upload_to='enregistrement/docs', verbose_name='Mandat de représentation'),
        ),
    ]
