# Generated by Django 4.2.14 on 2024-08-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0008_enregistrement_file_mandat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrement',
            name='file_mandat',
            field=models.FileField(blank=True, help_text="Si vous n'êtes pas le représentant légal, Joindre un mandat signé par le représentatnt légal de l'organisation", null=True, upload_to='docs/enregistrement', verbose_name='Mandat de représentation'),
        ),
        migrations.AlterField(
            model_name='enregistrement',
            name='file_piece',
            field=models.FileField(blank=True, null=True, upload_to='docs/enregistrement', verbose_name="Pièce d'identité"),
        ),
        migrations.AlterField(
            model_name='enregistrement',
            name='file_rccm',
            field=models.FileField(blank=True, null=True, upload_to='docs/enregistrement', verbose_name='Copie du Registre du Commerce'),
        ),
    ]
