# Generated by Django 4.2.14 on 2024-08-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0009_alter_enregistrement_file_mandat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Photo de profil (facultative)', max_length=255, null=True, upload_to='avatars', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='consentement',
            field=models.BooleanField(default=None, help_text="Veuillez cocher cette case pour donner votre consentement : \n        les données soumises via ce formulaire seront utilisées pour la création \n        et pour l'accomplissement de vos formalités sur la plateforme e-DCP. \n        Vos données ne seront traitées que par les agents habilités de l'Autorité de Protection.\n        Vous pouvez à tous moments exercer vos droits exercer à l'adresse ..... ", verbose_name='Recueil du consentement'),
            preserve_default=False,
        ),
    ]
