# Generated by Django 4.2.14 on 2024-08-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0014_alter_user_consentement'),
    ]

    operations = [
        migrations.AddField(
            model_name='enregistrement',
            name='idu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Numéro d'IDentifiant Unique"),
        ),
        migrations.AlterField(
            model_name='enregistrement',
            name='raisonsociale',
            field=models.CharField(blank=True, help_text="Nom de la personne physique ou de l'organisation enregistrée", max_length=100, verbose_name='Nom ou Raison Sociale'),
        ),
    ]
