# Generated by Django 4.2.14 on 2024-08-05 15:15

import base_edcp.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0018_alter_enregistrement_file_mandat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrement',
            name='adresse_geo',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[base_edcp.validators.validate_charfield, base_edcp.validators.validate_no_special_chars], verbose_name='Adresse Géographique'),
        ),
        migrations.AlterField(
            model_name='enregistrement',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email de Contact'),
        ),
        migrations.AlterField(
            model_name='enregistrement',
            name='presentation',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name="Présentation de l'activité"),
        ),
        migrations.AlterField(
            model_name='enregistrement',
            name='raisonsociale',
            field=models.CharField(help_text="Nom de la personne physique ou de l'organisation à enregistrer", max_length=100, validators=[base_edcp.validators.validate_charfield, base_edcp.validators.validate_no_special_chars], verbose_name='Nom ou Raison Sociale'),
        ),
        migrations.AlterField(
            model_name='enregistrement',
            name='secteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_edcp.secteur', verbose_name="Secteur d'Activité"),
        ),
        migrations.AlterField(
            model_name='enregistrement',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[base_edcp.validators.validate_phone_number], verbose_name='Téléphone'),
        ),
    ]
