# Generated by Django 4.2.14 on 2024-08-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0020_alter_enregistrement_file_mandat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrement',
            name='email_contact',
            field=models.EmailField(max_length=100, null=True, verbose_name='Email de Contact'),
        ),
    ]
