# Generated by Django 4.2.14 on 2024-08-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_edcp', '0021_alter_enregistrement_email_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_reset',
            field=models.BooleanField(default=False, verbose_name='Doit Reinitialiser son Mot de Passe'),
        ),
    ]
