# Generated by Django 4.2.14 on 2024-08-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demande', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de mise à jour'),
        ),
    ]
