# Nom du flux de travail
name: Les Vérifications et Déploiement

# Événement déclencheur
on:
  push:
    branches:
      - main # Seulement la branche principale (main)

# Définition des tâches à exécuter
jobs:
  test-lint: # Nom du job
    name: Test et Linting
    runs-on: ubuntu-20.04

    # Étapes à exécuter dans le job
    steps:
      - name: Se connecter à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Téléchargement du code source
        uses: actions/checkout@v2

      # - name: Exécuter les tests
      # run: docker-compose run --rm app_edcp sh -c "python manage.py test"

      # - name: Vérification du linting
      # run: docker-compose run --rm app_edcp sh -c "flake8"

  deploy:
    name: Déploiement
    runs-on: ubuntu-20.04
    needs: test-lint
    steps:
      - name: Se connecter à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Téléchargement du code source
        uses: actions/checkout@v2

      - name: Installer Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Construire l'image Docker avec tags sfourier
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/app_edcp:sfourier -t ${{ secrets.DOCKERHUB_USER }}/app_edcp:${{ github.sha }} .

      - name: Pousser l'image sur Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/app_edcp:sfourier
          docker push ${{ secrets.DOCKERHUB_USER }}/app_edcp:${{ github.sha }}